import { TSupportResponse, TSupportTicket } from "../types/support.schema";

export const supportTicketsMockData: TSupportTicket[] = [
  {
    id: "1",
    title: "Không thể upload ảnh bìa truyện",
    description:
      "Tôi gặp lỗi khi upload ảnh bìa cho truyện mới. Hệ thống báo lỗi 'File too large' nhưng file chỉ có 2MB.",
    type: "technical",
    status: "in_progress",
    priority: "medium",
    category: "technical",
    userId: "user123",
    userName: "Nguyễn Văn A",
    userEmail: "user123@example.com",
    assignedTo: "admin001",
    adminNote: "Đang kiểm tra giới hạn file size",
    createdAt: new Date("2024-08-05T09:30:00Z"),
    updatedAt: new Date("2024-08-05T11:15:00Z"),
    lastResponse: new Date("2024-08-05T11:15:00Z"),
  },
  {
    id: "2",
    title: "Đề xuất tính năng mới - Dark mode",
    description:
      "Tôi muốn đề xuất thêm tính năng dark mode cho dashboard để dễ sử dụng vào ban đêm.",
    type: "feature_request",
    status: "open",
    priority: "low",
    category: "general",
    userId: "user456",
    userName: "Trần Thị B",
    userEmail: "user456@example.com",
    createdAt: new Date("2024-08-04T16:20:00Z"),
    updatedAt: new Date("2024-08-04T16:20:00Z"),
  },
  {
    id: "3",
    title: "Lỗi tính toán thống kê lượt xem",
    description:
      "Số liệu thống kê lượt xem truyện của tôi có vẻ không chính xác. Hiển thị số âm.",
    type: "bug_report",
    status: "resolved",
    priority: "high",
    category: "technical",
    userId: "user789",
    userName: "Phạm Văn C",
    userEmail: "user789@example.com",
    assignedTo: "admin002",
    adminNote: "Đã sửa lỗi tính toán trong query database",
    resolvedAt: new Date("2024-08-03T14:30:00Z"),
    createdAt: new Date("2024-08-02T10:15:00Z"),
    updatedAt: new Date("2024-08-03T14:30:00Z"),
    lastResponse: new Date("2024-08-03T14:30:00Z"),
  },
  {
    id: "4",
    title: "Không thể đăng nhập vào tài khoản",
    description:
      "Tôi quên mật khẩu và không nhận được email reset. Vui lòng hỗ trợ khôi phục tài khoản.",
    type: "account_issue",
    status: "waiting_response",
    priority: "urgent",
    category: "account",
    userId: "user000",
    userName: "Lê Thị D",
    userEmail: "user000@example.com",
    assignedTo: "admin001",
    adminNote: "Đã gửi email reset mới, chờ phản hồi từ user",
    createdAt: new Date("2024-08-05T08:00:00Z"),
    updatedAt: new Date("2024-08-05T10:30:00Z"),
    lastResponse: new Date("2024-08-05T10:30:00Z"),
  },
  {
    id: "5",
    title: "Phản hồi về giao diện dashboard",
    description:
      "Giao diện dashboard rất đẹp nhưng tôi nghĩ nên thêm shortcut để tạo chương nhanh hơn.",
    type: "feedback",
    status: "closed",
    priority: "low",
    category: "general",
    userId: "user111",
    userName: "Hoàng Văn E",
    userEmail: "user111@example.com",
    assignedTo: "admin003",
    adminNote: "Cảm ơn feedback, sẽ cân nhắc trong phiên bản tiếp theo",
    resolvedAt: new Date("2024-08-01T15:45:00Z"),
    createdAt: new Date("2024-07-30T12:30:00Z"),
    updatedAt: new Date("2024-08-01T15:45:00Z"),
    lastResponse: new Date("2024-08-01T15:45:00Z"),
  },
  {
    id: "6",
    title: "Vấn đề thanh toán premium",
    description:
      "Tôi đã thanh toán gói premium nhưng tài khoản vẫn chưa được nâng cấp sau 24h.",
    type: "other",
    status: "in_progress",
    priority: "high",
    category: "billing",
    userId: "user222",
    userName: "Vũ Thị F",
    userEmail: "user222@example.com",
    assignedTo: "admin002",
    adminNote: "Đang kiểm tra với bộ phận tài chính",
    createdAt: new Date("2024-08-04T20:15:00Z"),
    updatedAt: new Date("2024-08-05T09:00:00Z"),
    lastResponse: new Date("2024-08-05T09:00:00Z"),
  },
];

export const supportResponsesMockData: TSupportResponse[] = [
  {
    id: "1",
    ticketId: "1",
    message:
      "Xin chào, chúng tôi đã nhận được báo cáo của bạn. Hiện tại giới hạn file upload là 5MB, vui lòng kiểm tra lại dung lượng file.",
    isAdminResponse: true,
    authorName: "Admin Support",
    authorEmail: "admin001@company.com",
    createdAt: new Date("2024-08-05T11:15:00Z"),
    updatedAt: new Date("2024-08-05T11:15:00Z"),
  },
  {
    id: "2",
    ticketId: "3",
    message:
      "Cảm ơn bạn đã báo cáo lỗi này. Chúng tôi đã xác định và sửa chữa vấn đề. Thống kê của bạn sẽ hiển thị chính xác trong vòng 24h tới.",
    isAdminResponse: true,
    authorName: "Technical Team",
    authorEmail: "admin002@company.com",
    createdAt: new Date("2024-08-03T14:30:00Z"),
    updatedAt: new Date("2024-08-03T14:30:00Z"),
  },
  {
    id: "3",
    ticketId: "4",
    message:
      "Chúng tôi đã gửi email reset password mới tới địa chỉ email đăng ký của bạn. Vui lòng kiểm tra cả thư mục spam. Nếu vẫn không nhận được, hãy liên hệ lại.",
    isAdminResponse: true,
    authorName: "Account Support",
    authorEmail: "admin001@company.com",
    createdAt: new Date("2024-08-05T10:30:00Z"),
    updatedAt: new Date("2024-08-05T10:30:00Z"),
  },
  {
    id: "4",
    ticketId: "6",
    message:
      "Chúng tôi đang kiểm tra giao dịch thanh toán của bạn với bộ phận tài chính. Sẽ có phản hồi trong vòng 24h. Xin lỗi vì sự bất tiện này.",
    isAdminResponse: true,
    authorName: "Billing Support",
    authorEmail: "admin002@company.com",
    createdAt: new Date("2024-08-05T09:00:00Z"),
    updatedAt: new Date("2024-08-05T09:00:00Z"),
  },
];
