import { TReport } from "../types/report.schema";

export const reportsMockData: TReport[] = [
  {
    id: "1",
    title: "Nội dung không phù hợp trong truyện",
    description:
      "Truyện có chứa nội dung bạo lực quá mức, không phù hợp với độ tuổi được ghi nhận.",
    type: "inappropriate_content",
    status: "pending",
    priority: "high",
    reportedBy: "user123",
    reportedUser: "author456",
    reportedContent: "Chương 15: Trận chiến cuối cùng",
    bookId: "book789",
    chapterId: "chapter101",
    createdAt: new Date("2024-08-05T10:30:00Z"),
    updatedAt: new Date("2024-08-05T10:30:00Z"),
  },
  {
    id: "2",
    title: "Spam comments trong truyện",
    description:
      "Có nhiều comment spam quảng cáo được đăng liên tục trong truyện này.",
    type: "spam",
    status: "reviewing",
    priority: "medium",
    reportedBy: "user789",
    reportedContent: "Comments section",
    bookId: "book456",
    adminNote: "Đang kiểm tra các comment được báo cáo",
    createdAt: new Date("2024-08-04T14:20:00Z"),
    updatedAt: new Date("2024-08-05T09:15:00Z"),
  },
  {
    id: "3",
    title: "Vi phạm bản quyền",
    description:
      "Truyện này được sao chép từ tác phẩm đã có bản quyền mà không có sự cho phép.",
    type: "copyright",
    status: "resolved",
    priority: "urgent",
    reportedBy: "publisher123",
    reportedUser: "copycat789",
    bookId: "book999",
    adminNote: "Đã xác nhận vi phạm bản quyền và gỡ truyện",
    resolvedBy: "admin001",
    resolvedAt: new Date("2024-08-03T16:45:00Z"),
    createdAt: new Date("2024-08-01T11:00:00Z"),
    updatedAt: new Date("2024-08-03T16:45:00Z"),
  },
  {
    id: "4",
    title: "Quấy rối người dùng khác",
    description:
      "Tác giả này liên tục quấy rối và chửi bới người dùng khác trong comments.",
    type: "harassment",
    status: "reviewing",
    priority: "high",
    reportedBy: "victim456",
    reportedUser: "bully123",
    bookId: "book333",
    adminNote: "Đang thu thập thêm bằng chứng",
    createdAt: new Date("2024-08-04T08:30:00Z"),
    updatedAt: new Date("2024-08-04T15:20:00Z"),
  },
  {
    id: "5",
    title: "Nội dung vi phạm quy định cộng đồng",
    description:
      "Truyện chứa nội dung phân biệt chủng tộc và kích động thù hận.",
    type: "violation",
    status: "rejected",
    priority: "medium",
    reportedBy: "user555",
    reportedUser: "author777",
    bookId: "book111",
    adminNote: "Sau khi xem xét, nội dung không vi phạm nghiêm trọng quy định",
    resolvedBy: "admin002",
    resolvedAt: new Date("2024-08-02T12:30:00Z"),
    createdAt: new Date("2024-07-30T09:15:00Z"),
    updatedAt: new Date("2024-08-02T12:30:00Z"),
  },
  {
    id: "6",
    title: "Báo cáo khác - Lỗi hiển thị",
    description: "Truyện bị lỗi hiển thị, không thể đọc được nội dung.",
    type: "other",
    status: "pending",
    priority: "low",
    reportedBy: "reader999",
    bookId: "book888",
    createdAt: new Date("2024-08-05T07:45:00Z"),
    updatedAt: new Date("2024-08-05T07:45:00Z"),
  },
];
