import { TChapter } from "../types/chapter.schema";

export const chaptersMockData: TChapter[] = [
  {
    id: "1",
    title: "Khởi đầu cuộc phiêu lưu",
    content: "Nội dung chương 1...",
    order: 1,
    status: "published",
    publishedDate: new Date("2024-01-01"),
    wordCount: 2500,
    bookId: "1",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    title: "Cuộc gặp gỡ định mệnh",
    content: "Nội dung chương 2...",
    order: 2,
    status: "published",
    publishedDate: new Date("2024-01-02"),
    wordCount: 3200,
    bookId: "1",
    createdAt: new Date("2024-01-02"),
    updatedAt: new Date("2024-01-02"),
  },
  {
    id: "3",
    title: "Thử thách đầu tiên",
    content: "Nội dung chương 3...",
    order: 3,
    status: "draft",
    wordCount: 1800,
    bookId: "1",
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-03"),
  },
  {
    id: "4",
    title: "Bí mật được tiết lộ",
    content: "Nội dung chương 4...",
    order: 4,
    status: "scheduled",
    publishedDate: new Date("2024-02-01"),
    wordCount: 2800,
    bookId: "1",
    createdAt: new Date("2024-01-04"),
    updatedAt: new Date("2024-01-04"),
  },
  {
    id: "5",
    title: "Chương mở đầu",
    content: "Nội dung chương 1 của truyện 2...",
    order: 1,
    status: "published",
    publishedDate: new Date("2024-01-05"),
    wordCount: 2200,
    bookId: "2",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
];
